### ISSUE TITLE
possibly add neutral/prestige research unlocks

### ISSUE THREAD

**Issue by nyanlathotep** [nyanlathotep/rg-plot#2]

**Comment by Unihedro** [comment]
R24+: Ancient Device: Get this before switching to neutral researches at around R28. (R25 is a easy point with proper planning)

R28 + 5k forges: UB quest <- negligible (source: me)
R29 + 2750th Excavation: Earth Core (require gems equal to end of R26 when using E290)
Unlock research quest: 100 QiSxg / 1e200, 10 M / 1e7 each FC (a lot harder than getting the artifact)
